### PR TITLE
Tell echolocation when nitrates fail

### PR DESCRIPTION
**Pull request by Tohuvavohu**
Reports ERROR to queue when BKG fails, or when no data is found after a day.
Reports COMPLETE to queue when exit due to no pointing data.

Any other failure modes missing that I  can catch to keep the queue clean and notify us of problems?

### CODE REVIEW

**Comment by jjd330** [comment]
What about for slews?

**Comment by Tohuvavohu** [comment]
Oh i do that too, just forgot to say. See line 1336 in do_manage in this PR.
It reports "complete" if no pointing data.

**Comment by Tohuvavohu** [comment]
Reports COMPLETE to queue when exit due to no pointing data.

did you mean something else?

**Comment by jjd330** [comment]
Thanks! Just saw that in the code too. Looks good to me. 
It will still miss the slews/no data that NITRATES misses where there's no usable data for the signal window (+/- 20s), but data available to do the bkg. But that's probably something that should be fixed inside of NITRATES first. Right now do_full_rates will just fail, then the split rate jobs will be submitted but also fail right away when there's no time seeds file.

**Review by jjd330 — APPROVED** [review]

**Comment by jjd330** [comment]
Feel free to merge if you're not making more edits

**Comment by Tohuvavohu** [comment]
Thanks @jjd330 

> It will still miss the slews/no data that NITRATES misses where there's no usable data for the signal window (+/- 20s), but data available to do the bkg. But that's probably something that should be fixed inside of NITRATES first. Right now do_full_rates will just fail, then the split rate jobs will be submitted but also fail right away when there's no time seeds file.

Can you open an issue for this?

**Pull request merged**
