### PR TITLE
Upload nitrates plots live

### PR DESCRIPTION
**Pull request by Tohuvavohu**
Adds functionality to do_full_rates and do_manage2 to create and upload nitrates results plots live, following implementation for achival results here https://github.com/Swift-BAT/NITRATES/pull/57

### CODE REVIEW

**Comment by jjd330** [comment]
Looks good looking through it. Just needs a test run, which hopefully someone else can do. I probably won't have time this week.

**Comment by Tohuvavohu** [comment]
i admit i dont remember why this never got merged. Doesn't the pipeline already do this now? 
@jjd330

**Comment by Tohuvavohu** [comment]
Ok i realized that the pipeline *doesnt* do this. It waits until the end to upload the plots.
Can we do a test run so this can be merged?

**Comment by jjd330** [comment]
I can do a test run of this after we get the roarcollab branch merged into main

**Comment by jjd330** [comment]
Test has been run and it worked successfully. Test can be seen here under config 99 https://guano.swift.psu.edu/trigger_report?id=746931808
Though the change was when the plots were uploaded and I confirmed that they the plots do upload as the analysis runs instead of just all at the end now.

**Review by jjd330 — APPROVED** [review]
Everything here is good and test was successful

**Pull request merged**
