### PR TITLE
Upload skymap figures

### PR DESCRIPTION
**Pull request by jjd330**
Updates to make the probability skymap figures and upload them inside of do_manage and in nitrates_reader.py. 
This has been tested and the uploaded skymap figures can be seen here
https://guano.swift.psu.edu/trigger_report?id=747657369

### CODE REVIEW

**Comment by jjd330** [comment]
I've also upped the version number and fixed a bug in LLH.py

**Review by Tohuvavohu — CHANGES_REQUESTED** [review]
Please describe the bug, did it negatively impact previous results?

Also, the zoom in seems to be useless for this trigger, given the max prob position is OFOV and without any gradient on that length scale?

**Comment by jjd330** [comment]
The bug stopped the bkg script from running if the number of rows in the GTI changed as it iterated through bkg windows doing fits. I haven't come across this error before or seen it and seems to be from an unfortunately placed data end time. It's possible though that it has effected something before though.

**Comment by Tohuvavohu** [comment]
How are you deciding on the size of the zoom region? Is it dynamic?

**Comment by jjd330** [comment]
Yeah, for this case, the zoom doesn't show much. I assume that will happen for most cases that have the max prob outside the FoV. I'm not sure if I want to not show in that case though. I don't really want to have 2 different color scales in the plots though.

**Comment by jjd330** [comment]
It's meant to show the IFOV regions well. Not much thought has gone into it showing OFOV detail as the full sky plot should be able to take care of that.

**Comment by Tohuvavohu** [comment]
Ok i would either get rid of the zoom plot if max prob is OFOV or change the plot so it shows some structure (if any there).

**Comment by jjd330** [comment]
The yellow dot is the Sun. I was going to say that in the documentation that its the Sun, but I'll add a legend or possibly a label on it. I'll see what looks best

**Comment by jjd330** [comment]
Ok plots have been updated on the page https://guano.swift.psu.edu/trigger_report?id=747657369 . 
The sun now looks like a sun and there was logic added so that in the zoom plot if the min / max probability is > 0.1 the zoom window increases from 10 deg to 20 deg. 
image
image

**Review by Tohuvavohu — APPROVED** [review]
LGTM!

**Pull request merged**
