### PR TITLE
Added cli to run reader from command line

### PR DESCRIPTION
**Pull request by samueleronchini**

### CODE REVIEW

**Comment by Tohuvavohu** [comment]
Will these changes still allow the codes that import functions from nitrates_reader to work properly?

**Comment by Tohuvavohu** [comment]
checks failed E    
 File "/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/nitrates-1.0.2-py3.8.egg/nitrates/post_process/nitrates_reader.py", line 844
E       if args.work_dir not None:
E                            ^
E   SyntaxError: invalid syntax

**Comment by Tohuvavohu** [comment]
This is not an executable, and is being imported by other parts of nitrates. please add if name==__main__ or whatever to embed the cli calls

**Comment by samueleronchini** [comment]
Ok, now it seems the checks have passed. Do I open another PR on Alfred to add:
python -m nitrates.post_process.nitrates_reader --work_dir ${workdir}
?

**Comment by Tohuvavohu** [comment]
Have you actually tested it?

**Comment by samueleronchini** [comment]
I get this when I test it:
read_results_dirs('%s' %args.work_dir)
TypeError: read_results_dirs() missing 1 required positional argument: 'api_token'

**Comment by samueleronchini** [comment]
and what I tested is 
python -m nitrates.post_process.nitrates_reader --work_dir /gpfs/group/jak51/default/nitrates_all_results/2023/tar/712491393_c0

**Comment by samueleronchini** [comment]
ok, with the inclusion of API token it works

**Comment by Tohuvavohu** [comment]
ok, in the future please try to test *before* opening a PR

**Review by Tohuvavohu — APPROVED** [review]

**Pull request merged**
