### PR TITLE
optimized model and LLH, slight response speed up

### PR DESCRIPTION
**Pull request by jjd330**
Added model, LLH, and response optimizations. Changed LLH in FoV script to use these updates. 
Everything is python 3 compatible and tested in python 3.10. Individual parts have been testes and a whole analysis has been run with no errors.  
See summary of changes below. 

**Changes in LLH.py**

- Added a LLH_webins2 class with updates to LLH_webins
- Works the same as LLH_webins, but expects the error to be error^2 instead of error 
- Has added support for models that return counts instead of rates (less multiplications) 
- Caches data dpis and other data products selected for certain time bins in a dictionary so they don't have to be remade 
- Added new pois_norm_conv_n*2 functions that take error^2 and are optimized to do less logs and exps 

**Changes in models.py**

- Made it so Source_Model_InOutFoV caches the normalized photon fluxes for each set of spectral params so it doesn't recalculate it every time set_flux_params is called. 
- New model, Sig_Bkg_Model added. 
- It takes an already made bkg model (any model is fine, that keeps all of it's parameters fixed), and a Source_Model_InOutFoV model. 
- Model only has one parameter, "A" that's used to update the signal DPIs in the Source_Model_InOutFoV model while keeping all other internal parameters fixed, bypassing calling any of the bkg models and keeping the bkg DPIs cached. 
- Also has new functions that return count DPIs instead of rate DPIs, that LLH_webins2 uses and saves time by not doing time exposure every LLH eval. 
- Also has new functions to get error DPIs squared, saves time by not doing the square root. LLH_webins2 support these new functions. 

**Changes in do_llh_inFoV4realtime2.py**

- Added the new model, Sig_Bkg_Model and LLH object, LLH_webins2.
- Changed how parameters and set and updated to reflect the new model used. 

**Changes in response.py**

- removed 2 unnecessary additions of large arrays in calc_tot_resp_dpis.

### CODE REVIEW

**Comment by jjd330** [comment]
Results of running prun on the do_analysis function in do_llh_inFoV4realtime2.py for just one position seed and 1 or 3 time seeds. With the current main branch (old) and this branch (new). 
[old_do_analysis_prun_3times.txt](https://github.com/Swift-BAT/NITRATES/files/9912524/old_do_analysis_prun_3times.txt)
[old_do_analysis_prun_1time.txt](https://github.com/Swift-BAT/NITRATES/files/9912525/old_do_analysis_prun_1time.txt)
[new_do_analysis_prun_1time.txt](https://github.com/Swift-BAT/NITRATES/files/9912526/new_do_analysis_prun_1time.txt)
[new_do_analysis_prun_3times.txt](https://github.com/Swift-BAT/NITRATES/files/9912527/new_do_analysis_prun_3times.txt)

**Comment by jjd330** [comment]
Hard to track the speed up accurately through a full analysis run, but on F688160018 it took ~2 hours to run after the seeding analyses, while it took ~3 hours to run with the current main branch. This was using 260 cores on the inFoV analysis and 40 cores on the outFoV analysis.

**Comment by jjd330** [comment]
Inside a single minimization, using data from I10018. The current main branch took about 6.6 ms/step while this branch took about 1.78 ms/step. Where for each step the model has to be updated to reflect the new spectral norm ("A"), the LLH has to be calculated, and the Jacobian also has to be calculated.

**Comment by jjd330** [comment]
Actually hold on, results from the full run are looking a little off. Checking that out right now.

**Comment by jjd330** [comment]
Think I found the issue. Rerunning the fully analysis now.

**Comment by jjd330** [comment]
Fixed the issue. Here's the results, they're the same as shown in the last pull request. 

In FoV results

<table border="1" class="dataframe">  <thead>    <tr style="text-align: right;">      <th></th>      <th>Unnamed: 0</th>      <th>imx</th>      <th>imy</th>      <th>theta</th>      <th>phi</th>      <th>Epeak</th>      <th>gamma</th>      <th>time</th>      <th>dur</th>      <th>timeID</th>      <th>bkg_nllh</th>      <th>nllh</th>      <th>A</th>      <th>TS</th>      <th>squareID</th>      <th>dt</th>      <th>ra</th>      <th>dec</th>      <th>fluence</th>      <th>pc</th>    </tr>  </thead>  <tbody>    <tr>      <th>669833</th>      <td>125</td>      <td>-0.798</td>      <td>0.634</td>      <td>45.544674</td>      <td>218.466657</td>      <td>918.973797</td>      <td>0.9</td>      <td>6.881600e+08</td>      <td>4.096</td>      <td>-40964096.0</td>      <td>38714.705313</td>      <td>38676.291940</td>      <td>0.001832</td>      <td>8.765087</td>      <td>1540</td>      <td>-4.096</td>      <td>118.341809</td>      <td>-5.116934</td>      <td>7.698506e-07</td>      <td>0.205608</td>    </tr>    <tr>      <th>519181</th>      <td>133</td>      <td>-1.105</td>      <td>0.727</td>      <td>52.909797</td>      <td>213.341660</td>      <td>918.973797</td>      <td>1.3</td>      <td>6.881600e+08</td>      <td>4.096</td>      <td>-40964096.0</td>      <td>38714.705315</td>      <td>38678.378279</td>      <td>0.002755</td>      <td>8.523736</td>      <td>1143</td>      <td>-4.096</td>      <td>123.282709</td>      <td>1.582015</td>      <td>9.188880e-07</td>      <td>0.130301</td>    </tr>    <tr>      <th>1580119</th>      <td>133</td>      <td>-0.621</td>      <td>0.640</td>      <td>41.725394</td>      <td>225.863233</td>      <td>918.973797</td>      <td>1.1</td>      <td>6.881600e+08</td>      <td>4.096</td>      <td>-40964096.0</td>      <td>38714.705312</td>      <td>38678.466363</td>      <td>0.001596</td>      <td>8.513395</td>      <td>1741</td>      <td>-4.096</td>      <td>116.615106</td>      <td>-11.253722</td>      <td>5.907977e-07</td>      <td>0.263801</td>    </tr>    <tr>      <th>1148542</th>      <td>124</td>      <td>-0.968</td>      <td>0.831</td>      <td>51.909185</td>      <td>220.645136</td>      <td>918.973797</td>      <td>1.3</td>      <td>6.881600e+08</td>      <td>4.096</td>      <td>-40964096.0</td>      <td>38714.705315</td>      <td>38678.592883</td>      <td>0.002956</td>      <td>8.498521</td>      <td>1295</td>      <td>-4.096</td>      <td>124.850977</td>      <td>-4.076380</td>      <td>9.860046e-07</td>      <td>0.080894</td>    </tr>    <tr>      <th>1494440</th>      <td>476</td>      <td>-0.622</td>      <td>0.640</td>      <td>41.747621</td>      <td>225.817159</td>      <td>918.973797</td>      <td>0.9</td>      <td>6.881600e+08</td>      <td>4.096</td>      <td>-40964096.0</td>      <td>38714.705313</td>      <td>38678.778789</td>      <td>0.001671</td>      <td>8.476618</td>      <td>1740</td>      <td>-4.096</td>      <td>116.626733</td>      <td>-11.217601</td>      <td>7.025202e-07</td>      <td>0.261941</td>    </tr>    <tr>      <th>1325447</th>      <td>125</td>      <td>-0.802</td>      <td>0.807</td>      <td>48.686624</td>      <td>225.178047</td>      <td>579.833267</td>      <td>0.9</td>      <td>6.881600e+08</td>      <td>4.096</td>      <td>-40964096.0</td>      <td>38714.705314</td>      <td>38679.214938</td>      <td>0.002777</td>      <td>8.425008</td>      <td>1545</td>      <td>-4.096</td>      <td>123.125485</td>      <td>-8.503022</td>      <td>8.776778e-07</td>      <td>0.106950</td>    </tr>    <tr>      <th>962873</th>      <td>107</td>      <td>-0.637</td>      <td>0.730</td>      <td>44.093555</td>      <td>228.891960</td>      <td>918.973797</td>      <td>0.9</td>      <td>6.881600e+08</td>      <td>4.096</td>      <td>-40964096.0</td>      <td>38714.705313</td>      <td>38679.268705</td>      <td>0.001930</td>      <td>8.418623</td>      <td>1743</td>      <td>-4.096</td>      <td>119.557873</td>      <td>-12.504587</td>      <td>8.112243e-07</td>      <td>0.177713</td>    </tr>    <tr>      <th>972098</th>      <td>98</td>      <td>-0.802</td>      <td>0.807</td>      <td>48.686624</td>      <td>225.178047</td>      <td>579.833267</td>      <td>0.9</td>      <td>6.881600e+08</td>      <td>4.096</td>      <td>-40964096.0</td>      <td>38714.705314</td>      <td>38679.376915</td>      <td>0.002829</td>      <td>8.405760</td>      <td>1495</td>      <td>-4.096</td>      <td>123.125485</td>      <td>-8.503022</td>      <td>8.943640e-07</td>      <td>0.106950</td>    </tr>    <tr>      <th>384569</th>      <td>143</td>      <td>-1.025</td>      <td>0.635</td>      <td>50.329233</td>      <td>211.778720</td>      <td>918.973797</td>      <td>1.2</td>      <td>6.881600e+08</td>      <td>4.096</td>      <td>-40964096.0</td>      <td>38714.705314</td>      <td>38679.830408</td>      <td>0.002108</td>      <td>8.351635</td>      <td>1240</td>      <td>-4.096</td>      <td>120.428199</td>      <td>1.451117</td>      <td>7.385842e-07</td>      <td>0.187500</td>    </tr>    <tr>      <th>1122794</th>      <td>134</td>      <td>-1.081</td>      <td>0.813</td>      <td>53.523882</td>      <td>216.946145</td>      <td>918.973797</td>      <td>1.4</td>      <td>6.881600e+08</td>      <td>4.096</td>      <td>-40964096.0</td>      <td>38714.705315</td>      <td>38679.856493</td>      <td>0.003037</td>      <td>8.348512</td>      <td>1195</td>      <td>-4.096</td>      <td>125.116687</td>      <td>-0.730348</td>      <td>9.718064e-07</td>      <td>0.088822</td>    </tr>    <tr>      <th>872494</th>      <td>124</td>      <td>-1.224</td>      <td>0.641</td>      <td>54.104737</td>      <td>207.640728</td>      <td>918.973797</td>      <td>1.3</td>      <td>6.881600e+08</td>      <td>4.096</td>      <td>-40964096.0</td>      <td>38714.705315</td>      <td>38679.921169</td>      <td>0.002758</td>      <td>8.340761</td>      <td>991</td>      <td>-4.096</td>      <td>122.083499</td>      <td>6.163974</td>      <td>9.200045e-07</td>      <td>0.150391</td>    </tr>    <tr>      <th>1462498</th>      <td>124</td>      <td>-1.224</td>      <td>0.641</td>      <td>54.104737</td>      <td>207.640728</td>      <td>918.973797</td>      <td>1.3</td>      <td>6.881600e+08</td>      <td>4.096</td>      <td>-40964096.0</td>      <td>38714.705315</td>      <td>38679.951395</td>      <td>0.002734</td>      <td>8.337136</td>      <td>990</td>      <td>-4.096</td>      <td>122.083499</td>      <td>6.163974</td>      <td>9.118686e-07</td>      <td>0.150391</td>    </tr>    <tr>      <th>970181</th>      <td>125</td>      <td>-0.688</td>      <td>0.738</td>      <td>45.255366</td>      <td>227.008146</td>      <td>918.973797</td>      <td>0.9</td>      <td>6.881600e+08</td>      <td>4.096</td>      <td>-40964096.0</td>      <td>38714.705314</td>      <td>38679.959348</td>      <td>0.001955</td>      <td>8.336182</td>      <td>1643</td>      <td>-4.096</td>      <td>120.281977</td>      <td>-10.891837</td>      <td>8.218915e-07</td>      <td>0.156250</td>    </tr>    <tr>      <th>1457149</th>      <td>121</td>      <td>-1.258</td>      <td>0.476</td>      <td>53.370275</td>      <td>200.725559</td>      <td>460.577935</td>      <td>0.6</td>      <td>6.881600e+08</td>      <td>4.096</td>      <td>-40964096.0</td>      <td>38714.705314</td>      <td>38680.075852</td>      <td>0.003097</td>      <td>8.322195</td>      <td>936</td>      <td>-4.096</td>      <td>118.372537</td>      <td>10.422699</td>      <td>8.600275e-07</td>      <td>0.217407</td>    </tr>    <tr>      <th>1457068</th>      <td>40</td>      <td>-1.258</td>      <td>0.476</td>      <td>53.370275</td>      <td>200.725559</td>      <td>460.577935</td>      <td>0.6</td>      <td>6.881600e+08</td>      <td>4.096</td>      <td>-40964096.0</td>      <td>38714.705314</td>      <td>38680.075852</td>      <td>0.003097</td>      <td>8.322195</td>      <td>936</td>      <td>-4.096</td>      <td>118.372537</td>      <td>10.422699</td>      <td>8.600275e-07</td>      <td>0.217407</td>    </tr>    <tr>      <th>693188</th>      <td>152</td>      <td>-0.646</td>      <td>0.693</td>      <td>43.452768</td>      <td>227.010304</td>      <td>918.973797</td>      <td>0.9</td>      <td>6.881600e+08</td>      <td>4.096</td>      <td>-40964096.0</td>      <td>38714.705313</td>      <td>38680.146771</td>      <td>0.001854</td>      <td>8.313669</td>      <td>1692</td>      <td>-4.096</td>      <td>118.535892</td>      <td>-11.453131</td>      <td>7.792122e-07</td>      <td>0.194327</td>    </tr>  </tbody></table>

Out of FoV results

<table border="1" class="dataframe">  <thead>    <tr style="text-align: right;">      <th></th>      <th>Unnamed: 0</th>      <th>theta</th>      <th>phi</th>      <th>time</th>      <th>dur</th>      <th>timeID</th>      <th>Epeak</th>      <th>gamma</th>      <th>nllh</th>      <th>A</th>      <th>TS</th>      <th>bkg_nllh</th>      <th>hp_ind</th>      <th>dt</th>      <th>ra</th>      <th>dec</th>    </tr>  </thead>  <tbody>    <tr>      <th>174518</th>      <td>30</td>      <td>64.721203</td>      <td>177.249965</td>      <td>6.881600e+08</td>      <td>4.096</td>      <td>-40964096.0</td>      <td>398.107171</td>      <td>2.4</td>      <td>38689.356285</td>      <td>0.003168</td>      <td>7.120257</td>      <td>38714.705315</td>      <td>396</td>      <td>-4.096</td>      <td>112.5000</td>      <td>32.797168</td>    </tr>    <tr>      <th>57558</th>      <td>30</td>      <td>64.219418</td>      <td>181.296636</td>      <td>6.881600e+08</td>      <td>4.096</td>      <td>-40964096.0</td>      <td>398.107171</td>      <td>2.4</td>      <td>38689.650207</td>      <td>0.003159</td>      <td>7.078857</td>      <td>38714.705315</td>      <td>390</td>      <td>-4.096</td>      <td>115.3125</td>      <td>30.000000</td>    </tr>    <tr>      <th>174514</th>      <td>26</td>      <td>64.721203</td>      <td>177.249965</td>      <td>6.881600e+08</td>      <td>4.096</td>      <td>-40964096.0</td>      <td>251.188643</td>      <td>2.2</td>      <td>38689.816818</td>      <td>0.003159</td>      <td>7.055281</td>      <td>38714.705315</td>      <td>396</td>      <td>-4.096</td>      <td>112.5000</td>      <td>32.797168</td>    </tr>    <tr>      <th>88566</th>      <td>30</td>      <td>60.546439</td>      <td>181.313981</td>      <td>6.881600e+08</td>      <td>4.096</td>      <td>-40964096.0</td>      <td>398.107171</td>      <td>2.4</td>      <td>38689.863066</td>      <td>0.003105</td>      <td>7.048723</td>      <td>38714.705315</td>      <td>387</td>      <td>-4.096</td>      <td>112.5000</td>      <td>27.279613</td>    </tr>    <tr>      <th>98902</th>      <td>30</td>      <td>59.314010</td>      <td>168.462838</td>      <td>6.881600e+08</td>      <td>4.096</td>      <td>-40964096.0</td>      <td>398.107171</td>      <td>2.4</td>      <td>38689.949959</td>      <td>0.002876</td>      <td>7.036385</td>      <td>38714.705315</td>      <td>416</td>      <td>-4.096</td>      <td>101.2500</td>      <td>32.797168</td>    </tr>    <tr>      <th>174521</th>      <td>33</td>      <td>64.721203</td>      <td>177.249965</td>      <td>6.881600e+08</td>      <td>4.096</td>      <td>-40964096.0</td>      <td>630.957344</td>      <td>2.4</td>      <td>38690.003461</td>      <td>0.003656</td>      <td>7.028777</td>      <td>38714.705315</td>      <td>396</td>      <td>-4.096</td>      <td>112.5000</td>      <td>32.797168</td>    </tr>    <tr>      <th>167582</th>      <td>30</td>      <td>65.546622</td>      <td>173.266206</td>      <td>6.881600e+08</td>      <td>4.096</td>      <td>-40964096.0</td>      <td>398.107171</td>      <td>2.4</td>      <td>38690.010963</td>      <td>0.003147</td>      <td>7.027710</td>      <td>38714.705315</td>      <td>398</td>      <td>-4.096</td>      <td>109.6875</td>      <td>35.685335</td>    </tr>    <tr>      <th>57554</th>      <td>26</td>      <td>64.219418</td>      <td>181.296636</td>      <td>6.881600e+08</td>      <td>4.096</td>      <td>-40964096.0</td>      <td>251.188643</td>      <td>2.2</td>      <td>38690.091497</td>      <td>0.003148</td>      <td>7.016241</td>      <td>38714.705315</td>      <td>390</td>      <td>-4.096</td>      <td>115.3125</td>      <td>30.000000</td>    </tr>    <tr>      <th>174517</th>      <td>29</td>      <td>64.721203</td>      <td>177.249965</td>      <td>6.881600e+08</td>      <td>4.096</td>      <td>-40964096.0</td>      <td>398.107171</td>      <td>2.2</td>      <td>38690.104242</td>      <td>0.003503</td>      <td>7.014424</td>      <td>38714.705315</td>      <td>396</td>      <td>-4.096</td>      <td>112.5000</td>      <td>32.797168</td>    </tr>    <tr>      <th>174507</th>      <td>19</td>      <td>64.721203</td>      <td>177.249965</td>      <td>6.881600e+08</td>      <td>4.096</td>      <td>-40964096.0</td>      <td>398.107171</td>      <td>2.2</td>      <td>38690.104242</td>      <td>0.003503</td>      <td>7.014424</td>      <td>38714.705315</td>      <td>396</td>      <td>-4.096</td>      <td>112.5000</td>      <td>32.797168</td>    </tr>    <tr>      <th>174520</th>      <td>32</td>      <td>64.721203</td>      <td>177.249965</td>      <td>6.881600e+08</td>      <td>4.096</td>      <td>-40964096.0</td>      <td>630.957344</td>      <td>2.2</td>      <td>38690.204638</td>      <td>0.003644</td>      <td>7.000097</td>      <td>38714.705315</td>      <td>396</td>      <td>-4.096</td>      <td>112.5000</td>      <td>32.797168</td>    </tr>    <tr>      <th>174512</th>      <td>24</td>      <td>64.721203</td>      <td>177.249965</td>      <td>6.881600e+08</td>      <td>4.096</td>      <td>-40964096.0</td>      <td>1000.000000</td>      <td>2.2</td>      <td>38690.247951</td>      <td>0.003725</td>      <td>6.993907</td>      <td>38714.705315</td>      <td>396</td>      <td>-4.096</td>      <td>112.5000</td>      <td>32.797168</td>    </tr>    <tr>      <th>321398</th>      <td>30</td>      <td>61.036706</td>      <td>177.143326</td>      <td>6.881600e+08</td>      <td>4.096</td>      <td>-40964096.0</td>      <td>398.107171</td>      <td>2.4</td>      <td>38690.273453</td>      <td>0.003008</td>      <td>6.990259</td>      <td>38714.705315</td>      <td>393</td>      <td>-4.096</td>      <td>109.6875</td>      <td>30.000000</td>    </tr>    <tr>      <th>57561</th>      <td>33</td>      <td>64.219418</td>      <td>181.296636</td>      <td>6.881600e+08</td>      <td>4.096</td>      <td>-40964096.0</td>      <td>630.957344</td>      <td>2.4</td>      <td>38690.305440</td>      <td>0.003648</td>      <td>6.985682</td>      <td>38714.705315</td>      <td>390</td>      <td>-4.096</td>      <td>115.3125</td>      <td>30.000000</td>    </tr>    <tr>      <th>98898</th>      <td>26</td>      <td>59.314010</td>      <td>168.462838</td>      <td>6.881600e+08</td>      <td>4.096</td>      <td>-40964096.0</td>      <td>251.188643</td>      <td>2.2</td>      <td>38690.316333</td>      <td>0.002875</td>      <td>6.984122</td>      <td>38714.705315</td>      <td>416</td>      <td>-4.096</td>      <td>101.2500</td>      <td>32.797168</td>    </tr>    <tr>      <th>88562</th>      <td>26</td>      <td>60.546439</td>      <td>181.313981</td>      <td>6.881600e+08</td>      <td>4.096</td>      <td>-40964096.0</td>      <td>251.188643</td>      <td>2.2</td>      <td>38690.325667</td>      <td>0.003087</td>      <td>6.982786</td>      <td>38714.705315</td>      <td>387</td>      <td>-4.096</td>      <td>112.5000</td>      <td>27.279613</td>    </tr>  </tbody></table>

**Comment by Tohuvavohu** [comment]
LGTM

**Pull request merged**
