### PR TITLE
Use config file 

### PR DESCRIPTION
**Pull request by Tohuvavohu**
Closes https://github.com/Swift-BAT/NITRATES/issues/18

Still WIP.

Define new Config object that reads in config.json
Clean up do_data_setup to remove unused args
Pass config parameters to do_data_setup from config object

### CODE REVIEW

**Comment by Tohuvavohu** [comment]
This PR includes do_data_prep and do_full_rates read.

it does not currently include new features, like switch for "BkgSrcPosFit" or the API info needed to report back to queue.

**Comment by Tohuvavohu** [comment]
@jjd330 If this PR looks good, do you think you can try a full loop test, using the QueueListener.py in Alfred to launch a search using this version of nitrates?

**Comment by Tohuvavohu** [comment]
Now some report-back features via EchoAPI

This requires analyze_trigger.sh to pass the api_token to the scripts using the new --api_token command line argument.
Let me know if you think there's a better way to handle this.

**Comment by jjd330** [comment]
Yeah, I think that should be a fine way to include it. I'll try to have the analyze_trigger.sh read the token from a file.
I'll give this a full test today.

**Comment by jjd330** [comment]
Getting this error
`The do_data_setup.py call failed. Check the data_setup.log`
and having trouble finding where it's coming from. There's nothing in the data_setup.log. The log file exists but it's empty.

**Comment by jjd330** [comment]
Full run in still going, but pushed fixes for the small bugs so far

**Comment by Tohuvavohu** [comment]
@jjd330 Ready for another test run

**Comment by jjd330** [comment]
Results from this look good
https://guano.swift.psu.edu/trigger_report?id=704233771

**Pull request merged**
