### PR TITLE
updating realtime_public branch with main

### PR DESCRIPTION
**Pull request by g3-raman**

### CODE REVIEW

**Comment by Tohuvavohu** [comment]
See the conflicts that need to be resolved before merge is allowed, it looks like these are just the paths.

**Comment by Tohuvavohu** [comment]
This PR is not requesting a merge to main...
Can you help me understand what you are trying to do here?

**Comment by g3-raman** [comment]
Oh, like Jimmy mentioned, this PR is to eventually merge the local branch
'realtime_public_v2' into the main. This branch now has the recent changes
made by Jimmy along with what is being run currently on the cluster. I will
submit a test run and match results with a previously submitted trigger and
then this can be merged to main.

**Comment by g3-raman** [comment]
Ran offline tests on three triggers  C1364594810, IC1378068756840 and F701928594.
 
 Attached are test results for C1364594810 - email outputs for the automated run and the test offline run with the latest changes adopted. The results are identical.
 
[C1364594810.pdf](https://github.com/Swift-BAT/NITRATES/files/11276558/C1364594810.pdf)
[C1364594810_test.pdf](https://github.com/Swift-BAT/NITRATES/files/11276559/C1364594810_test.pdf)

**Pull request merged**
