### PR TITLE
Merging roarcolab branch into main

### PR DESCRIPTION
**Pull request by jjd330**
Finally merging the roarcolab branch that's been running on roar for a couple of months now. 
Most of the changes have been to paths in config, and new support for submitting slurm jobs in do_manage2. 
There are also some small changes that accrued over time, like changing the default data DB name.

### CODE REVIEW

**Comment by parsotat** [comment]
I'm not sure that any of these are necessary to be in the main branch which is supposed to be general. These seem to all be specific to roar collab, no?

**Comment by jjd330** [comment]
Yes, these changes are all specific to roar collab. We were (as of a couple of month ago) having main be what runs on roar. Do we want to instead keep running a roar specific branch that we just keep up to date with main?

**Comment by Tohuvavohu** [comment]
What was the resolution here? we should set a standard.

**Comment by Tohuvavohu** [comment]
My perspective, as always, is that we should move all the data scraping/prep and do_manage into Alfred, and it should call NITRATES as a general purpose analysis tool, with necessary configuration arguments.

**Comment by jjd330** [comment]
@parsotat Is there anything here that would mess up what's running on NCCS? If not, I'd like to merge this to get main caught up to the new stuff to make probability skymaps and updated responses. 
I can move do_manage and the other scripts to Alfred in the next update

**Comment by Tohuvavohu** [comment]
There is a conflict, see checks @jjd330

**Comment by jjd330** [comment]
conflict resolved

**Comment by jjd330** [comment]
Permission from Tyler via slack. Merging

**Pull request merged**
