### PR TITLE
Residual batml updates

### PR DESCRIPTION
**Pull request by jjd330**
Added in some updates I've done in the private repo. 

do_manage2.py - 
- Made it so that long ssh cmds are split up (there's a limit to length)
- added a --q arg to pass to sub_jobs, which is needed to submit jobs to the virtual queue
- create started directories to put files in that say if each seed has been started for in and out of FoV LLH jobs

do_llh_inFoV4realtime2.py - 
- Made it so that each job, when it starts processing a seed, will create a file saying it has started
- Skips and seed that has already been started
- Each job, after it has finished its own seeds will check the other jobs' seeds to see if they have been started, and if not, will run them

do_llh_oFoV4realtime2.py - 
- Made it so that each job, when it starts processing a seed, will create a file saying it has started
- Skips and seed that has already been started
- Each job, after it has finished its own seeds will check the other jobs' seeds to see if they have been started, and if not, will run them

do_rates_mle_InOutFoV2.py - 
- Made it so that it doesn't crash if there's no partial coding image to use

pyscript_template_rhel7.pbs - 
- Added arg pmem, which give memory per processor and lets the multi-core bkg job have more memory

### CODE REVIEW

**Comment by Tohuvavohu** [comment]
Are all these commits py3 compatible?

**Comment by jjd330** [comment]
Yep, this should all be python 3 compatible.

**Comment by Tohuvavohu** [comment]
have these been run on cluster?

**Comment by jjd330** [comment]
No, not this exact branch. Do you want me to run a full search with it on the cluster?

**Comment by Tohuvavohu** [comment]
If not to difficult. then we can merge with confidence

**Comment by jjd330** [comment]
Ok, I can get on that later today.

**Comment by jjd330** [comment]
Should be all good now. Full test analysis ran without errors. 
Corrected a couple small mistakes I made, and found some stuff that already didn't work (importing stuff from config.py that doesn't exist anymore).

**Comment by Tohuvavohu** [comment]
Without errors and with matching results? can you paste top results here for posterity? :)
Then i will merger.

**Comment by jjd330** [comment]
I ran F688160018 and the in FoV results match Gayathri's emailed results. The out FoV results don't match her email because her top oFoV results are actually in FoV. There's nothing in the changes here that should change any of the results, it only changes what 

LLH in FoV results 

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Unnamed: 0</th>
      <th>imx</th>
      <th>imy</th>
      <th>theta</th>
      <th>phi</th>
      <th>Epeak</th>
      <th>gamma</th>
      <th>time</th>
      <th>dur</th>
      <th>timeID</th>
      <th>bkg_nllh</th>
      <th>nllh</th>
      <th>A</th>
      <th>TS</th>
      <th>squareID</th>
      <th>ra</th>
      <th>dec</th>
      <th>cls</th>
      <th>dt</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>152</th>
      <td>152</td>
      <td>-0.646</td>
      <td>0.693</td>
      <td>43.452768</td>
      <td>227.010304</td>
      <td>918.973797</td>
      <td>0.9</td>
      <td>6.881600e+08</td>
      <td>4.096</td>
      <td>-40964096</td>
      <td>38714.705313</td>
      <td>38680.146771</td>
      <td>0.001854</td>
      <td>8.313669</td>
      <td>1692</td>
      <td>118.535892</td>
      <td>-11.453131</td>
      <td>0.025931</td>
      <td>-4.096</td>
    </tr>
    <tr>
      <th>40</th>
      <td>40</td>
      <td>-1.258</td>
      <td>0.476</td>
      <td>53.370275</td>
      <td>200.725559</td>
      <td>460.577935</td>
      <td>0.6</td>
      <td>6.881600e+08</td>
      <td>4.096</td>
      <td>-40964096</td>
      <td>38714.705314</td>
      <td>38680.075853</td>
      <td>0.003097</td>
      <td>8.322195</td>
      <td>936</td>
      <td>118.372537</td>
      <td>10.422699</td>
      <td>0.227737</td>
      <td>-4.096</td>
    </tr>
    <tr>
      <th>125</th>
      <td>125</td>
      <td>-0.688</td>
      <td>0.738</td>
      <td>45.255366</td>
      <td>227.008146</td>
      <td>918.973797</td>
      <td>0.9</td>
      <td>6.881600e+08</td>
      <td>4.096</td>
      <td>-40964096</td>
      <td>38714.705314</td>
      <td>38679.959348</td>
      <td>0.001955</td>
      <td>8.336182</td>
      <td>1643</td>
      <td>120.281977</td>
      <td>-10.891837</td>
      <td>0.027266</td>
      <td>-4.096</td>
    </tr>
    <tr>
      <th>124</th>
      <td>124</td>
      <td>-1.224</td>
      <td>0.641</td>
      <td>54.104737</td>
      <td>207.640728</td>
      <td>918.973797</td>
      <td>1.3</td>
      <td>6.881600e+08</td>
      <td>4.096</td>
      <td>-40964096</td>
      <td>38714.705315</td>
      <td>38679.941996</td>
      <td>0.002732</td>
      <td>8.338263</td>
      <td>990</td>
      <td>122.083499</td>
      <td>6.163974</td>
      <td>0.147147</td>
      <td>-4.096</td>
    </tr>
    <tr>
      <th>124</th>
      <td>124</td>
      <td>-1.224</td>
      <td>0.641</td>
      <td>54.104737</td>
      <td>207.640728</td>
      <td>918.973797</td>
      <td>1.3</td>
      <td>6.881600e+08</td>
      <td>4.096</td>
      <td>-40964096</td>
      <td>38714.705315</td>
      <td>38679.911443</td>
      <td>0.002756</td>
      <td>8.341927</td>
      <td>991</td>
      <td>122.083499</td>
      <td>6.163974</td>
      <td>0.147147</td>
      <td>-4.096</td>
    </tr>
    <tr>
      <th>134</th>
      <td>134</td>
      <td>-1.081</td>
      <td>0.813</td>
      <td>53.523882</td>
      <td>216.946145</td>
      <td>918.973797</td>
      <td>1.4</td>
      <td>6.881600e+08</td>
      <td>4.096</td>
      <td>-40964096</td>
      <td>38714.705315</td>
      <td>38679.856493</td>
      <td>0.003037</td>
      <td>8.348512</td>
      <td>1195</td>
      <td>125.116687</td>
      <td>-0.730348</td>
      <td>0.139933</td>
      <td>-4.096</td>
    </tr>
    <tr>
      <th>143</th>
      <td>143</td>
      <td>-1.025</td>
      <td>0.635</td>
      <td>50.329233</td>
      <td>211.778720</td>
      <td>918.973797</td>
      <td>1.2</td>
      <td>6.881600e+08</td>
      <td>4.096</td>
      <td>-40964096</td>
      <td>38714.705314</td>
      <td>38679.830408</td>
      <td>0.002108</td>
      <td>8.351635</td>
      <td>1240</td>
      <td>120.428199</td>
      <td>1.451117</td>
      <td>0.126743</td>
      <td>-4.096</td>
    </tr>
    <tr>
      <th>98</th>
      <td>98</td>
      <td>-0.802</td>
      <td>0.807</td>
      <td>48.686624</td>
      <td>225.178047</td>
      <td>579.833267</td>
      <td>0.9</td>
      <td>6.881600e+08</td>
      <td>4.096</td>
      <td>-40964096</td>
      <td>38714.705314</td>
      <td>38679.376915</td>
      <td>0.002829</td>
      <td>8.405760</td>
      <td>1495</td>
      <td>123.125485</td>
      <td>-8.503022</td>
      <td>0.019802</td>
      <td>-4.096</td>
    </tr>
    <tr>
      <th>107</th>
      <td>107</td>
      <td>-0.637</td>
      <td>0.730</td>
      <td>44.093555</td>
      <td>228.891960</td>
      <td>918.973797</td>
      <td>0.9</td>
      <td>6.881600e+08</td>
      <td>4.096</td>
      <td>-40964096</td>
      <td>38714.705313</td>
      <td>38679.268705</td>
      <td>0.001930</td>
      <td>8.418623</td>
      <td>1743</td>
      <td>119.557873</td>
      <td>-12.504587</td>
      <td>0.011994</td>
      <td>-4.096</td>
    </tr>
    <tr>
      <th>125</th>
      <td>125</td>
      <td>-0.802</td>
      <td>0.807</td>
      <td>48.686624</td>
      <td>225.178047</td>
      <td>579.833267</td>
      <td>0.9</td>
      <td>6.881600e+08</td>
      <td>4.096</td>
      <td>-40964096</td>
      <td>38714.705314</td>
      <td>38679.214938</td>
      <td>0.002777</td>
      <td>8.425008</td>
      <td>1545</td>
      <td>123.125485</td>
      <td>-8.503022</td>
      <td>0.019802</td>
      <td>-4.096</td>
    </tr>
    <tr>
      <th>476</th>
      <td>476</td>
      <td>-0.622</td>
      <td>0.640</td>
      <td>41.747621</td>
      <td>225.817159</td>
      <td>918.973797</td>
      <td>0.9</td>
      <td>6.881600e+08</td>
      <td>4.096</td>
      <td>-40964096</td>
      <td>38714.705313</td>
      <td>38678.778789</td>
      <td>0.001671</td>
      <td>8.476618</td>
      <td>1740</td>
      <td>116.626733</td>
      <td>-11.217601</td>
      <td>0.111686</td>
      <td>-4.096</td>
    </tr>
    <tr>
      <th>124</th>
      <td>124</td>
      <td>-0.968</td>
      <td>0.831</td>
      <td>51.909185</td>
      <td>220.645136</td>
      <td>918.973797</td>
      <td>1.3</td>
      <td>6.881600e+08</td>
      <td>4.096</td>
      <td>-40964096</td>
      <td>38714.705315</td>
      <td>38678.592883</td>
      <td>0.002956</td>
      <td>8.498521</td>
      <td>1295</td>
      <td>124.850977</td>
      <td>-4.076380</td>
      <td>0.137192</td>
      <td>-4.096</td>
    </tr>
    <tr>
      <th>133</th>
      <td>133</td>
      <td>-0.621</td>
      <td>0.640</td>
      <td>41.725394</td>
      <td>225.863233</td>
      <td>918.973797</td>
      <td>1.1</td>
      <td>6.881600e+08</td>
      <td>4.096</td>
      <td>-40964096</td>
      <td>38714.705312</td>
      <td>38678.466362</td>
      <td>0.001596</td>
      <td>8.513395</td>
      <td>1741</td>
      <td>116.615106</td>
      <td>-11.253722</td>
      <td>0.111686</td>
      <td>-4.096</td>
    </tr>
    <tr>
      <th>133</th>
      <td>133</td>
      <td>-1.105</td>
      <td>0.727</td>
      <td>52.909797</td>
      <td>213.341660</td>
      <td>918.973797</td>
      <td>1.3</td>
      <td>6.881600e+08</td>
      <td>4.096</td>
      <td>-40964096</td>
      <td>38714.705315</td>
      <td>38678.378279</td>
      <td>0.002755</td>
      <td>8.523736</td>
      <td>1143</td>
      <td>123.282709</td>
      <td>1.582015</td>
      <td>0.082727</td>
      <td>-4.096</td>
    </tr>
    <tr>
      <th>125</th>
      <td>125</td>
      <td>-0.798</td>
      <td>0.634</td>
      <td>45.544674</td>
      <td>218.466657</td>
      <td>918.973797</td>
      <td>0.9</td>
      <td>6.881600e+08</td>
      <td>4.096</td>
      <td>-40964096</td>
      <td>38714.705313</td>
      <td>38676.291940</td>
      <td>0.001832</td>
      <td>8.765087</td>
      <td>1540</td>
      <td>118.341809</td>
      <td>-5.116934</td>
      <td>0.095355</td>
      <td>-4.096</td>
    </tr>
  </tbody>
</table>

LLH out of FoV results (not sure why there's all the "\n"s. 

<table border="1" class="dataframe">\n  <thead>\n    <tr style="text-align: right;">\n      <th></th>\n      <th>Unnamed: 0</th>\n      <th>theta</th>\n      <th>phi</th>\n      <th>time</th>\n      <th>dur</th>\n      <th>timeID</th>\n      <th>Epeak</th>\n      <th>gamma</th>\n      <th>nllh</th>\n      <th>A</th>\n      <th>TS</th>\n      <th>bkg_nllh</th>\n      <th>hp_ind</th>\n      <th>dt</th>\n      <th>ra</th>\n      <th>dec</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>156022</th>\n      <td>30</td>\n      <td>64.721203</td>\n      <td>177.249965</td>\n      <td>6.881600e+08</td>\n      <td>4.096</td>\n      <td>-40964096.0</td>\n      <td>398.107171</td>\n      <td>2.4</td>\n      <td>38689.356285</td>\n      <td>0.003168</td>\n      <td>7.120257</td>\n      <td>38714.705315</td>\n      <td>396</td>\n      <td>-4.096</td>\n      <td>112.5000</td>\n      <td>32.797168</td>\n    </tr>\n    <tr>\n      <th>52118</th>\n      <td>30</td>\n      <td>64.219418</td>\n      <td>181.296636</td>\n      <td>6.881600e+08</td>\n      <td>4.096</td>\n      <td>-40964096.0</td>\n      <td>398.107171</td>\n      <td>2.4</td>\n      <td>38689.650207</td>\n      <td>0.003159</td>\n      <td>7.078857</td>\n      <td>38714.705315</td>\n      <td>390</td>\n      <td>-4.096</td>\n      <td>115.3125</td>\n      <td>30.000000</td>\n    </tr>\n    <tr>\n      <th>156018</th>\n      <td>26</td>\n      <td>64.721203</td>\n      <td>177.249965</td>\n      <td>6.881600e+08</td>\n      <td>4.096</td>\n      <td>-40964096.0</td>\n      <td>251.188643</td>\n      <td>2.2</td>\n      <td>38689.816818</td>\n      <td>0.003159</td>\n      <td>7.055281</td>\n      <td>38714.705315</td>\n      <td>396</td>\n      <td>-4.096</td>\n      <td>112.5000</td>\n      <td>32.797168</td>\n    </tr>\n    <tr>\n      <th>81086</th>\n      <td>30</td>\n      <td>60.546439</td>\n      <td>181.313981</td>\n      <td>6.881600e+08</td>\n      <td>4.096</td>\n      <td>-40964096.0</td>\n      <td>398.107171</td>\n      <td>2.4</td>\n      <td>38689.863066</td>\n      <td>0.003105</td>\n      <td>7.048723</td>\n      <td>38714.705315</td>\n      <td>387</td>\n      <td>-4.096</td>\n      <td>112.5000</td>\n      <td>27.279613</td>\n    </tr>\n    <tr>\n      <th>90198</th>\n      <td>30</td>\n      <td>59.314010</td>\n      <td>168.462838</td>\n      <td>6.881600e+08</td>\n      <td>4.096</td>\n      <td>-40964096.0</td>\n      <td>398.107171</td>\n      <td>2.4</td>\n      <td>38689.949959</td>\n      <td>0.002876</td>\n      <td>7.036385</td>\n      <td>38714.705315</td>\n      <td>416</td>\n      <td>-4.096</td>\n      <td>101.2500</td>\n      <td>32.797168</td>\n    </tr>\n    <tr>\n      <th>156025</th>\n      <td>33</td>\n      <td>64.721203</td>\n      <td>177.249965</td>\n      <td>6.881600e+08</td>\n      <td>4.096</td>\n      <td>-40964096.0</td>\n      <td>630.957344</td>\n      <td>2.4</td>\n      <td>38690.003461</td>\n      <td>0.003656</td>\n      <td>7.028777</td>\n      <td>38714.705315</td>\n      <td>396</td>\n      <td>-4.096</td>\n      <td>112.5000</td>\n      <td>32.797168</td>\n    </tr>\n    <tr>\n      <th>150310</th>\n      <td>30</td>\n      <td>65.546622</td>\n      <td>173.266206</td>\n      <td>6.881600e+08</td>\n      <td>4.096</td>\n      <td>-40964096.0</td>\n      <td>398.107171</td>\n      <td>2.4</td>\n      <td>38690.010963</td>\n      <td>0.003147</td>\n      <td>7.027710</td>\n      <td>38714.705315</td>\n      <td>398</td>\n      <td>-4.096</td>\n      <td>109.6875</td>\n      <td>35.685335</td>\n    </tr>\n    <tr>\n      <th>52114</th>\n      <td>26</td>\n      <td>64.219418</td>\n      <td>181.296636</td>\n      <td>6.881600e+08</td>\n      <td>4.096</td>\n      <td>-40964096.0</td>\n      <td>251.188643</td>\n      <td>2.2</td>\n      <td>38690.091497</td>\n      <td>0.003148</td>\n      <td>7.016241</td>\n      <td>38714.705315</td>\n      <td>390</td>\n      <td>-4.096</td>\n      <td>115.3125</td>\n      <td>30.000000</td>\n    </tr>\n    <tr>\n      <th>156021</th>\n      <td>29</td>\n      <td>64.721203</td>\n      <td>177.249965</td>\n      <td>6.881600e+08</td>\n      <td>4.096</td>\n      <td>-40964096.0</td>\n      <td>398.107171</td>\n      <td>2.2</td>\n      <td>38690.104242</td>\n      <td>0.003503</td>\n      <td>7.014424</td>\n      <td>38714.705315</td>\n      <td>396</td>\n      <td>-4.096</td>\n      <td>112.5000</td>\n      <td>32.797168</td>\n    </tr>\n    <tr>\n      <th>156011</th>\n      <td>19</td>\n      <td>64.721203</td>\n      <td>177.249965</td>\n      <td>6.881600e+08</td>\n      <td>4.096</td>\n      <td>-40964096.0</td>\n      <td>398.107171</td>\n      <td>2.2</td>\n      <td>38690.104242</td>\n      <td>0.003503</td>\n      <td>7.014424</td>\n      <td>38714.705315</td>\n      <td>396</td>\n      <td>-4.096</td>\n      <td>112.5000</td>\n      <td>32.797168</td>\n    </tr>\n    <tr>\n      <th>156024</th>\n      <td>32</td>\n      <td>64.721203</td>\n      <td>177.249965</td>\n      <td>6.881600e+08</td>\n      <td>4.096</td>\n      <td>-40964096.0</td>\n      <td>630.957344</td>\n      <td>2.2</td>\n      <td>38690.204638</td>\n      <td>0.003644</td>\n      <td>7.000097</td>\n      <td>38714.705315</td>\n      <td>396</td>\n      <td>-4.096</td>\n      <td>112.5000</td>\n      <td>32.797168</td>\n    </tr>\n    <tr>\n      <th>156016</th>\n      <td>24</td>\n      <td>64.721203</td>\n      <td>177.249965</td>\n      <td>6.881600e+08</td>\n      <td>4.096</td>\n      <td>-40964096.0</td>\n      <td>1000.000000</td>\n      <td>2.2</td>\n      <td>38690.247951</td>\n      <td>0.003725</td>\n      <td>6.993907</td>\n      <td>38714.705315</td>\n      <td>396</td>\n      <td>-4.096</td>\n      <td>112.5000</td>\n      <td>32.797168</td>\n    </tr>\n    <tr>\n      <th>284406</th>\n      <td>30</td>\n      <td>61.036706</td>\n      <td>177.143326</td>\n      <td>6.881600e+08</td>\n      <td>4.096</td>\n      <td>-40964096.0</td>\n      <td>398.107171</td>\n      <td>2.4</td>\n      <td>38690.273453</td>\n      <td>0.003008</td>\n      <td>6.990259</td>\n      <td>38714.705315</td>\n      <td>393</td>\n      <td>-4.096</td>\n      <td>109.6875</td>\n      <td>30.000000</td>\n    </tr>\n    <tr>\n      <th>52121</th>\n      <td>33</td>\n      <td>64.219418</td>\n      <td>181.296636</td>\n      <td>6.881600e+08</td>\n      <td>4.096</td>\n      <td>-40964096.0</td>\n      <td>630.957344</td>\n      <td>2.4</td>\n      <td>38690.305440</td>\n      <td>0.003648</td>\n      <td>6.985682</td>\n      <td>38714.705315</td>\n      <td>390</td>\n      <td>-4.096</td>\n      <td>115.3125</td>\n      <td>30.000000</td>\n    </tr>\n    <tr>\n      <th>90194</th>\n      <td>26</td>\n      <td>59.314010</td>\n      <td>168.462838</td>\n      <td>6.881600e+08</td>\n      <td>4.096</td>\n      <td>-40964096.0</td>\n      <td>251.188643</td>\n      <td>2.2</td>\n      <td>38690.316333</td>\n      <td>0.002875</td>\n      <td>6.984122</td>\n      <td>38714.705315</td>\n      <td>416</td>\n      <td>-4.096</td>\n      <td>101.2500</td>\n      <td>32.797168</td>\n    </tr>\n    <tr>\n      <th>81082</th>\n      <td>26</td>\n      <td>60.546439</td>\n      <td>181.313981</td>\n      <td>6.881600e+08</td>\n      <td>4.096</td>\n      <td>-40964096.0</td>\n      <td>251.188643</td>\n      <td>2.2</td>\n      <td>38690.325667</td>\n      <td>0.003087</td>\n      <td>6.982786</td>\n      <td>38714.705315</td>\n      <td>387</td>\n      <td>-4.096</td>\n      <td>112.5000</td>\n      <td>27.279613</td>\n    </tr>\n  </tbody>\n</table>

**Comment by Tohuvavohu** [comment]
Can you explain why gayathri's ofov results are different? Is it because she is running without a PC image?

**Comment by jjd330** [comment]
Yep, it's because she doesn't have the partial coding image. Without it the out of FoV part of the analysis does the whole sky instead of just at points with <5% coding.

**Comment by Tohuvavohu** [comment]
LGTM, merging

**Pull request merged**
