### PR TITLE
Making NITRATES Pip Installable 

### PR DESCRIPTION
**Pull request by parsotat**
I have tested the code and made sure that it runs and verified that the jupyter notebooks produce the same output.

The code still needs to be tested on a high performance computing environment and have some hardcoded paths changed.

[Example_LLH_setup_fixed_dirs_py3_pip.pdf](https://github.com/Swift-BAT/NITRATES/files/9203547/Example_LLH_setup_fixed_dirs_py3_pip.pdf)
[Example_Reading_Results_py3_pip.pdf](https://github.com/Swift-BAT/NITRATES/files/9203551/Example_Reading_Results_py3_pip.pdf)

[Example_LLH_setup_fixed_dirs_py2_no_debug.pdf](https://github.com/Swift-BAT/NITRATES/files/9203552/Example_LLH_setup_fixed_dirs_py2_no_debug.pdf)
[Example_Reading_Results_py2_no_debug.pdf](https://github.com/Swift-BAT/NITRATES/files/9203554/Example_Reading_Results_py2_no_debug.pdf)

### CODE REVIEW

**Comment by Tohuvavohu** [comment]
I think all we need is a successful full run on the cluster with identical results, and then this can be merged (modulo catching up on a few commits that are behind).

**Comment by jjd330** [comment]
This line https://github.com/parsotat/NITRATES/blob/main/nitrates/llh_analysis/do_llh_outFoV4realtime2.py#L39 ,
should be importing `get_out_res_fnames` instead of `get_in_res_fnames`

**Comment by jjd330** [comment]
Running the search with this fork and the pennstate branch of UtilityBelt https://github.com/Swift-BAT/UtilityBelt/tree/pennstate gave me identical results to the realtime search for trigger F704233744. To run the search I ran it as
. [analyze_trigger.sh](https://github.com/Swift-BAT/UtilityBelt/blob/pennstate/analyze_trigger.sh)  F704233744 /storage/work/jjd330/local/NITRATES_pipinstall/F704233744/ 2023-04-26T20:28:59.97



LLH in FoV analysis results around Peaks
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Unnamed: 0</th>
      <th>imx</th>
      <th>imy</th>
      <th>theta</th>
      <th>phi</th>
      <th>Epeak</th>
      <th>gamma</th>
      <th>time</th>
      <th>dur</th>
      <th>timeID</th>
      <th>bkg_nllh</th>
      <th>nllh</th>
      <th>A</th>
      <th>TS</th>
      <th>squareID</th>
      <th>ra</th>
      <th>dec</th>
      <th>dt</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>273</th>
      <td>273</td>
      <td>-1.563</td>
      <td>0.311</td>
      <td>57.891971</td>
      <td>191.253525</td>
      <td>212.132034</td>
      <td>-2.000000e-01</td>
      <td>7.042338e+08</td>
      <td>16.384</td>
      <td>819216384</td>
      <td>86608.427801</td>
      <td>84089.225496</td>
      <td>0.059285</td>
      <td>70.981720</td>
      <td>582</td>
      <td>92.418634</td>
      <td>-81.064842</td>
      <td>8.192</td>
    </tr>
    <tr>
      <th>291</th>
      <td>291</td>
      <td>-1.559</td>
      <td>0.347</td>
      <td>57.948699</td>
      <td>192.548263</td>
      <td>212.132034</td>
      <td>-2.000000e-01</td>
      <td>7.042338e+08</td>
      <td>16.384</td>
      <td>819216384</td>
      <td>86608.427801</td>
      <td>84088.755853</td>
      <td>0.060086</td>
      <td>70.988336</td>
      <td>583</td>
      <td>89.739837</td>
      <td>-80.057966</td>
      <td>8.192</td>
    </tr>
    <tr>
      <th>432</th>
      <td>432</td>
      <td>-1.249</td>
      <td>-0.077</td>
      <td>51.370831</td>
      <td>176.472219</td>
      <td>365.850058</td>
      <td>-2.000000e-01</td>
      <td>7.042338e+08</td>
      <td>16.384</td>
      <td>819216384</td>
      <td>86608.427789</td>
      <td>84086.239452</td>
      <td>0.020318</td>
      <td>71.023775</td>
      <td>923</td>
      <td>177.569520</td>
      <td>-78.809483</td>
      <td>8.192</td>
    </tr>
    <tr>
      <th>300</th>
      <td>300</td>
      <td>-1.561</td>
      <td>0.239</td>
      <td>57.656541</td>
      <td>188.704786</td>
      <td>212.132034</td>
      <td>-2.000000e-01</td>
      <td>7.042338e+08</td>
      <td>16.384</td>
      <td>819216384</td>
      <td>86608.427801</td>
      <td>84083.786709</td>
      <td>0.059186</td>
      <td>71.058301</td>
      <td>581</td>
      <td>100.982988</td>
      <td>-82.879864</td>
      <td>8.192</td>
    </tr>
    <tr>
      <th>921</th>
      <td>921</td>
      <td>-1.107</td>
      <td>0.401</td>
      <td>49.657578</td>
      <td>199.912427</td>
      <td>460.577935</td>
      <td>-2.000000e-01</td>
      <td>7.042338e+08</td>
      <td>16.384</td>
      <td>819216384</td>
      <td>86608.427784</td>
      <td>84082.546493</td>
      <td>0.015458</td>
      <td>71.075752</td>
      <td>1134</td>
      <td>109.024282</td>
      <td>-70.946451</td>
      <td>8.192</td>
    </tr>
    <tr>
      <th>453</th>
      <td>453</td>
      <td>-1.199</td>
      <td>-0.063</td>
      <td>50.209781</td>
      <td>176.992229</td>
      <td>460.577935</td>
      <td>-2.000000e-01</td>
      <td>7.042338e+08</td>
      <td>16.384</td>
      <td>819216384</td>
      <td>86608.427784</td>
      <td>84082.484368</td>
      <td>0.014222</td>
      <td>71.076626</td>
      <td>1023</td>
      <td>173.483105</td>
      <td>-77.897591</td>
      <td>8.192</td>
    </tr>
    <tr>
      <th>777</th>
      <td>777</td>
      <td>-1.145</td>
      <td>0.147</td>
      <td>49.099167</td>
      <td>187.315858</td>
      <td>460.577935</td>
      <td>-2.000000e-01</td>
      <td>7.042338e+08</td>
      <td>16.384</td>
      <td>819216384</td>
      <td>86608.427777</td>
      <td>84081.416729</td>
      <td>0.013450</td>
      <td>71.091646</td>
      <td>1078</td>
      <td>137.170151</td>
      <td>-76.696262</td>
      <td>8.192</td>
    </tr>
    <tr>
      <th>616</th>
      <td>616</td>
      <td>-1.181</td>
      <td>0.435</td>
      <td>51.530903</td>
      <td>200.220363</td>
      <td>460.577935</td>
      <td>-1.000000e-01</td>
      <td>7.042338e+08</td>
      <td>16.384</td>
      <td>819216384</td>
      <td>86608.427789</td>
      <td>84080.909231</td>
      <td>0.016964</td>
      <td>71.098784</td>
      <td>1035</td>
      <td>103.611932</td>
      <td>-71.698025</td>
      <td>8.192</td>
    </tr>
    <tr>
      <th>1242</th>
      <td>1242</td>
      <td>-1.209</td>
      <td>0.411</td>
      <td>51.934941</td>
      <td>198.775484</td>
      <td>365.850058</td>
      <td>-2.000000e-01</td>
      <td>7.042338e+08</td>
      <td>16.384</td>
      <td>819216384</td>
      <td>86608.427790</td>
      <td>84078.107287</td>
      <td>0.022153</td>
      <td>71.138182</td>
      <td>985</td>
      <td>104.241363</td>
      <td>-72.886934</td>
      <td>8.192</td>
    </tr>
    <tr>
      <th>918</th>
      <td>918</td>
      <td>-1.253</td>
      <td>0.427</td>
      <td>52.931707</td>
      <td>198.818192</td>
      <td>365.850058</td>
      <td>-2.775558e-17</td>
      <td>7.042338e+08</td>
      <td>16.384</td>
      <td>819216384</td>
      <td>86608.427793</td>
      <td>84076.509631</td>
      <td>0.022867</td>
      <td>71.160637</td>
      <td>935</td>
      <td>101.158067</td>
      <td>-73.325308</td>
      <td>8.192</td>
    </tr>
    <tr>
      <th>1263</th>
      <td>1263</td>
      <td>-1.201</td>
      <td>0.357</td>
      <td>51.405757</td>
      <td>196.554702</td>
      <td>460.577935</td>
      <td>-2.000000e-01</td>
      <td>7.042338e+08</td>
      <td>16.384</td>
      <td>819216384</td>
      <td>86608.427786</td>
      <td>84074.848285</td>
      <td>0.015773</td>
      <td>71.183980</td>
      <td>1033</td>
      <td>109.104989</td>
      <td>-74.072485</td>
      <td>8.192</td>
    </tr>
    <tr>
      <th>1611</th>
      <td>1611</td>
      <td>-1.201</td>
      <td>0.357</td>
      <td>51.405757</td>
      <td>196.554702</td>
      <td>365.850058</td>
      <td>-2.000000e-01</td>
      <td>7.042338e+08</td>
      <td>16.384</td>
      <td>819216384</td>
      <td>86608.427788</td>
      <td>84074.278676</td>
      <td>0.021031</td>
      <td>71.191981</td>
      <td>983</td>
      <td>109.104989</td>
      <td>-74.072485</td>
      <td>8.192</td>
    </tr>
    <tr>
      <th>1084</th>
      <td>1084</td>
      <td>-1.167</td>
      <td>0.375</td>
      <td>50.791980</td>
      <td>197.814121</td>
      <td>460.577935</td>
      <td>-1.000000e-01</td>
      <td>7.042338e+08</td>
      <td>16.384</td>
      <td>819216384</td>
      <td>86608.427787</td>
      <td>84072.332415</td>
      <td>0.016337</td>
      <td>71.219314</td>
      <td>1034</td>
      <td>108.892883</td>
      <td>-72.917631</td>
      <td>8.192</td>
    </tr>
    <tr>
      <th>777</th>
      <td>777</td>
      <td>-1.107</td>
      <td>0.403</td>
      <td>49.673964</td>
      <td>200.003882</td>
      <td>460.577935</td>
      <td>-2.000000e-01</td>
      <td>7.042338e+08</td>
      <td>16.384</td>
      <td>819216384</td>
      <td>86608.427784</td>
      <td>84065.730454</td>
      <td>0.015712</td>
      <td>71.311953</td>
      <td>1135</td>
      <td>108.865487</td>
      <td>-70.897109</td>
      <td>8.192</td>
    </tr>
    <tr>
      <th>423</th>
      <td>423</td>
      <td>-1.213</td>
      <td>-0.109</td>
      <td>50.610791</td>
      <td>174.865201</td>
      <td>365.850058</td>
      <td>-2.000000e-01</td>
      <td>7.042338e+08</td>
      <td>16.384</td>
      <td>819216384</td>
      <td>86608.427788</td>
      <td>84064.234602</td>
      <td>0.019654</td>
      <td>71.332926</td>
      <td>972</td>
      <td>181.266572</td>
      <td>-77.558516</td>
      <td>8.192</td>
    </tr>
    <tr>
      <th>939</th>
      <td>939</td>
      <td>-1.125</td>
      <td>0.423</td>
      <td>50.238909</td>
      <td>200.606261</td>
      <td>460.577935</td>
      <td>-2.000000e-01</td>
      <td>7.042338e+08</td>
      <td>16.384</td>
      <td>819216384</td>
      <td>86608.427787</td>
      <td>84059.166521</td>
      <td>0.016476</td>
      <td>71.403939</td>
      <td>1085</td>
      <td>106.660471</td>
      <td>-70.803898</td>
      <td>8.192</td>
    </tr>
  </tbody>
</table>



LLH out of FoV analysis results
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Unnamed: 0</th>
      <th>theta</th>
      <th>phi</th>
      <th>time</th>
      <th>dur</th>
      <th>timeID</th>
      <th>Epeak</th>
      <th>gamma</th>
      <th>nllh</th>
      <th>A</th>
      <th>TS</th>
      <th>bkg_nllh</th>
      <th>hp_ind</th>
      <th>ra</th>
      <th>dec</th>
      <th>dt</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>132</th>
      <td>132</td>
      <td>68.188162</td>
      <td>192.583302</td>
      <td>7.042338e+08</td>
      <td>16.384</td>
      <td>819216384</td>
      <td>1000.000000</td>
      <td>2.4</td>
      <td>83689.654283</td>
      <td>0.032834</td>
      <td>76.403842</td>
      <td>86608.427807</td>
      <td>2057</td>
      <td>33.748882</td>
      <td>-78.285144</td>
      <td>8.192</td>
    </tr>
    <tr>
      <th>114</th>
      <td>114</td>
      <td>68.188162</td>
      <td>192.583302</td>
      <td>7.042338e+08</td>
      <td>16.384</td>
      <td>819216384</td>
      <td>158.489319</td>
      <td>1.0</td>
      <td>83688.359217</td>
      <td>0.063240</td>
      <td>76.420790</td>
      <td>86608.427807</td>
      <td>2057</td>
      <td>33.748882</td>
      <td>-78.285144</td>
      <td>8.192</td>
    </tr>
    <tr>
      <th>129</th>
      <td>129</td>
      <td>68.188162</td>
      <td>192.583302</td>
      <td>7.042338e+08</td>
      <td>16.384</td>
      <td>819216384</td>
      <td>630.957344</td>
      <td>2.4</td>
      <td>83687.084977</td>
      <td>0.031259</td>
      <td>76.437462</td>
      <td>86608.427807</td>
      <td>2057</td>
      <td>33.748882</td>
      <td>-78.285144</td>
      <td>8.192</td>
    </tr>
    <tr>
      <th>127</th>
      <td>127</td>
      <td>68.188162</td>
      <td>192.583302</td>
      <td>7.042338e+08</td>
      <td>16.384</td>
      <td>819216384</td>
      <td>630.957344</td>
      <td>2.0</td>
      <td>83685.517088</td>
      <td>0.030773</td>
      <td>76.457972</td>
      <td>86608.427807</td>
      <td>2057</td>
      <td>33.748882</td>
      <td>-78.285144</td>
      <td>8.192</td>
    </tr>
    <tr>
      <th>130</th>
      <td>130</td>
      <td>68.188162</td>
      <td>192.583302</td>
      <td>7.042338e+08</td>
      <td>16.384</td>
      <td>819216384</td>
      <td>1000.000000</td>
      <td>2.0</td>
      <td>83685.517088</td>
      <td>0.030773</td>
      <td>76.457972</td>
      <td>86608.427807</td>
      <td>2057</td>
      <td>33.748882</td>
      <td>-78.285144</td>
      <td>8.192</td>
    </tr>
    <tr>
      <th>133</th>
      <td>133</td>
      <td>68.188162</td>
      <td>192.583302</td>
      <td>7.042338e+08</td>
      <td>16.384</td>
      <td>819216384</td>
      <td>1584.893192</td>
      <td>2.0</td>
      <td>83685.517088</td>
      <td>0.030773</td>
      <td>76.457972</td>
      <td>86608.427807</td>
      <td>2057</td>
      <td>33.748882</td>
      <td>-78.285144</td>
      <td>8.192</td>
    </tr>
    <tr>
      <th>130</th>
      <td>130</td>
      <td>71.250268</td>
      <td>193.943382</td>
      <td>7.042338e+08</td>
      <td>16.384</td>
      <td>819216384</td>
      <td>158.489319</td>
      <td>0.8</td>
      <td>83685.422034</td>
      <td>0.072814</td>
      <td>76.459215</td>
      <td>86608.427810</td>
      <td>2059</td>
      <td>26.999243</td>
      <td>-75.341631</td>
      <td>8.192</td>
    </tr>
    <tr>
      <th>121</th>
      <td>121</td>
      <td>68.188162</td>
      <td>192.583302</td>
      <td>7.042338e+08</td>
      <td>16.384</td>
      <td>819216384</td>
      <td>398.107171</td>
      <td>2.2</td>
      <td>83684.561593</td>
      <td>0.029898</td>
      <td>76.470468</td>
      <td>86608.427807</td>
      <td>2057</td>
      <td>33.748882</td>
      <td>-78.285144</td>
      <td>8.192</td>
    </tr>
    <tr>
      <th>131</th>
      <td>131</td>
      <td>71.250268</td>
      <td>193.943382</td>
      <td>7.042338e+08</td>
      <td>16.384</td>
      <td>819216384</td>
      <td>158.489319</td>
      <td>1.0</td>
      <td>83683.228943</td>
      <td>0.063374</td>
      <td>76.487893</td>
      <td>86608.427810</td>
      <td>2059</td>
      <td>26.999243</td>
      <td>-75.341631</td>
      <td>8.192</td>
    </tr>
    <tr>
      <th>114</th>
      <td>114</td>
      <td>71.250268</td>
      <td>193.943382</td>
      <td>7.042338e+08</td>
      <td>16.384</td>
      <td>819216384</td>
      <td>158.489319</td>
      <td>1.0</td>
      <td>83683.228943</td>
      <td>0.063374</td>
      <td>76.487893</td>
      <td>86608.427810</td>
      <td>2059</td>
      <td>26.999243</td>
      <td>-75.341631</td>
      <td>8.192</td>
    </tr>
    <tr>
      <th>132</th>
      <td>132</td>
      <td>71.250268</td>
      <td>193.943382</td>
      <td>7.042338e+08</td>
      <td>16.384</td>
      <td>819216384</td>
      <td>158.489319</td>
      <td>1.2</td>
      <td>83683.201949</td>
      <td>0.054949</td>
      <td>76.488246</td>
      <td>86608.427810</td>
      <td>2059</td>
      <td>26.999243</td>
      <td>-75.341631</td>
      <td>8.192</td>
    </tr>
    <tr>
      <th>128</th>
      <td>128</td>
      <td>68.188162</td>
      <td>192.583302</td>
      <td>7.042338e+08</td>
      <td>16.384</td>
      <td>819216384</td>
      <td>630.957344</td>
      <td>2.2</td>
      <td>83678.648231</td>
      <td>0.031287</td>
      <td>76.547757</td>
      <td>86608.427807</td>
      <td>2057</td>
      <td>33.748882</td>
      <td>-78.285144</td>
      <td>8.192</td>
    </tr>
    <tr>
      <th>115</th>
      <td>115</td>
      <td>68.188162</td>
      <td>192.583302</td>
      <td>7.042338e+08</td>
      <td>16.384</td>
      <td>819216384</td>
      <td>158.489319</td>
      <td>1.6</td>
      <td>83678.133051</td>
      <td>0.041877</td>
      <td>76.554487</td>
      <td>86608.427807</td>
      <td>2057</td>
      <td>33.748882</td>
      <td>-78.285144</td>
      <td>8.192</td>
    </tr>
    <tr>
      <th>131</th>
      <td>131</td>
      <td>68.188162</td>
      <td>192.583302</td>
      <td>7.042338e+08</td>
      <td>16.384</td>
      <td>819216384</td>
      <td>1000.000000</td>
      <td>2.2</td>
      <td>83677.196605</td>
      <td>0.032060</td>
      <td>76.566719</td>
      <td>86608.427807</td>
      <td>2057</td>
      <td>33.748882</td>
      <td>-78.285144</td>
      <td>8.192</td>
    </tr>
    <tr>
      <th>126</th>
      <td>126</td>
      <td>68.188162</td>
      <td>192.583302</td>
      <td>7.042338e+08</td>
      <td>16.384</td>
      <td>819216384</td>
      <td>1000.000000</td>
      <td>2.2</td>
      <td>83677.196605</td>
      <td>0.032060</td>
      <td>76.566719</td>
      <td>86608.427807</td>
      <td>2057</td>
      <td>33.748882</td>
      <td>-78.285144</td>
      <td>8.192</td>
    </tr>
    <tr>
      <th>134</th>
      <td>134</td>
      <td>68.188162</td>
      <td>192.583302</td>
      <td>7.042338e+08</td>
      <td>16.384</td>
      <td>819216384</td>
      <td>1584.893192</td>
      <td>2.2</td>
      <td>83676.761637</td>
      <td>0.032527</td>
      <td>76.572399</td>
      <td>86608.427807</td>
      <td>2057</td>
      <td>33.748882</td>
      <td>-78.285144</td>
      <td>8.192</td>
    </tr>
  </tbody>
</table>

**Review by Tohuvavohu — APPROVED** [review]
LGTM

**Pull request merged**
